### ISSUE TITLE
Interpretation of the results

### ISSUE THREAD

**Issue by Jurys22** [chiayewken/Span-ASTE#14]
Hello,
I was looking at the file in

`/content/Span-ASTE/model_outputs/aste_sample_c7b00b66bf7ec669d23b80879fda043d/predict_dev.jsonl`

I would like to know what are the numbers in the predicted_ner and predicted_relations such as:

`[[0, 0, 1, 1, 'NEG', 2.777, 0.971]]`

What are 2.777 and 0.971 referring to?

Thank you

**Comment by chiayewken** [comment]
Hi, [2.777, 0.971] are referring to [raw_score, softmax_score]. For reference, there are further details of the document format in [document.py](https://github.com/chiayewken/Span-ASTE/blob/c25751355a664278a4320b46c8abd1dcf4c32078/span_model/data/dataset_readers/document.py#L413)

**Comment by JiahuiSophieHU** [comment]
Hello, 
I notice that the **triples list** is sometimes empty while **target and opinion spans** are extracted (files are: sentences_dev_pred.json and sentences_dev_gold.json).

Does it mean that the model fails to predict polarity or to pair up found spans? 
Thank you

Pred: {"tokens": ["I", "also", "ordered", "for", "delivery", "and", "the", "restaurant", "forgot", "half", "the", "order", "."], "pos": [], "weight": 1, "id": 11, "is_labeled": false, **"triples": [], "spans": [[4, 4, "TARGET"], [8, 8, "OPINION"]]**}

Gold: "tokens": ["I", "also", "ordered", "for", "delivery", "and", "the", "restaurant", "forgot", "half", "the", "order", "."], "pos": ["O", "O", "O", "O", "O", "O", "O", "O", "s", "O", "O", "O", "O"], "weight": 1, "id": 11, "is_labeled": false, "triples": [{"o_start": 8, "o_end": 8, "t_start": 4, "t_end": 4, "label": "NEG"}, {"o_start": 8, "o_end": 8, "t_start": 11, "t_end": 11, "label": "NEG"}], "spans": []}

**Comment by chiayewken** [comment]
Hi, it means that the model did not pair up the spans.
