### ISSUE TITLE
Span Mask MLM

### ISSUE THREAD

**Issue by BigSalmon2** [chiayewken/Span-ASTE#2]
Can I use this to [MASK] spans?

**Comment by chiayewken** [comment]
Hi, the model was trained with a sentiment triplet extraction objective which extracts triplets of (target term, opinion term, sentiment polarity), for example the image below. Hence, I think it is different from the masked language model objective that you are looking for.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/29782952/127321685-5af758a6-d3a5-47f6-b3cf-9d639edc7911.png">

**Comment by chiayewken** [comment]
Hi, thank you for your interest in our work, the aste folder contains the code to facilitate experiments:
- data_util.py is for data preparation and processing
- evaluation.py contains scoring functions on the ASTE task
- main.py and main.sh are scripts for launching the model training experiments
- parsing.py and utils.py are miscellaneous additional functions

**Comment by dingtingtings** [comment]
Thank you for your reply really. But  I  have a new problem,  When the code runs, there is an error in the main.py,  named"ModuleNotFoundError: No module named 'span_model'" .   I found that the root of the error was in utils.py --> run_command -->  o = process.stdout.readline().decode() ， So,  in the main.py --> SpanModelTrainer -->train -->  shell.run()，are the parameters correct?  and  "AssertionError " in "assert self.model_path.exists() "

**Comment by chiayewken** [comment]
Hi, sorry I am unable to reproduce your error, can I check if you are running the commands based on the usage section in the readme? A working example is also demonstrated in the [Colab Notebook](https://colab.research.google.com/drive/1F9zW_nVkwfwIVXTOA_juFDrlPz5TLjpK?usp=sharing).

**Comment by dingtingtings** [comment]
thank you for your reply.I have solved the problems mentioned above. Whether the hyperparameter value "use_distance_embeds" is  True  in file aste.jsonnet, it"s  False in  code.

**Comment by dingtingtings** [comment]
Hello, thank you for your reply! I want to ask you a question. I want to draw the epoch -Loss changing curve, but I don"t find the total loss after per epoch in the code, I'm not familiar with allennlp, and there is no  relevant information on the Internet

**Comment by chiayewken** [comment]
Hi, one way is to manually save the training statistics to file, and analyse the files after training. You can modify line 392 of "span_model/models/span_model.py" to save the "output_dict" which should contain the training metadata.

**Comment by lilililisa1998** [comment]
> Thank you for your reply really. But I have a new problem, When the code runs, there is an error in the main.py, named"ModuleNotFoundError: No module named 'span_model'" . I found that the root of the error was in utils.py --> run_command --> o = process.stdout.readline().decode() ， So, in the main.py --> SpanModelTrainer -->train --> shell.run()，are the parameters correct? and "AssertionError " in "assert self.model_path.exists() 


> "AssertionError " in "assert self.model_path.exists()，请问您的model_path不存在问题解决了吗？

**Comment by dingtingtings** [comment]
> 

![image](https://user-images.githubusercontent.com/59607675/165745003-56abdf75-6c6d-495c-96ba-069da7e44329.png)
在main.py中的train函数中的shell.run()函数中的include_package参数的值改为图片中所示，试一下

**Comment by chiayewken** [comment]
Hi, we recently updated to a new and simpler API which uses wrapper.py and not main.py, can you try the training steps in this notebook? https://github.com/chiayewken/Span-ASTE/blob/main/demo.ipynb

```
from wrapper import SpanModel

model = SpanModel(save_dir=save_dir, random_seed=random_seed)
model.fit(path_train, path_dev)

model.predict(path_in=path_test, path_out=path_pred)
results = model.score(path_pred, path_test)
```
