### ISSUE TITLE
Train model for new data collected from social media

### ISSUE THREAD

**Issue by Lafandi** [chiayewken/Span-ASTE#20]
Hi, I would like to train this model in a new dataset with another language "Bahasa" as aspects and opinions of them, especially in social media textual data, constitute a span of words with multiple lengths. How to execute the file accordingly?

**Comment by chiayewken** [comment]
Hi, first you need to tokenize the sentences into separated words and follow the [annotation format guide and sample data file](https://github.com/chiayewken/Span-ASTE/blob/main/README.md#data-format). For the model [training stage](https://github.com/chiayewken/Span-ASTE/blob/main/README.md#model-training) and [prediction stage](https://github.com/chiayewken/Span-ASTE/blob/main/README.md#model-evaluation), you can change the `path_train`, `path_dev` and `path_test` to point to your data files.

**Comment by Lafandi** [comment]
> Hi, first you need to tokenize the sentences into separated words and follow the [annotation format guide and sample data file](https://github.com/chiayewken/Span-ASTE/blob/main/README.md#data-format). For the model [training stage](https://github.com/chiayewken/Span-ASTE/blob/main/README.md#model-training) and [prediction stage](https://github.com/chiayewken/Span-ASTE/blob/main/README.md#model-evaluation), you can change the `path_train`, `path_dev` and `path_test` to point to your data files.

Thank you for your guidance. I am new to data science; thank you, Sire, for your haste reply.

**Comment by Lafandi** [comment]
Hi,
Dr. Chia greetings,
:)

May I know if there is gonna be a maximum span limit for any aspect or
opinion?


Thanks in advance,
Regards.

**Comment by chiayewken** [comment]
Hi, you can change the span width limit here: https://github.com/chiayewken/Span-ASTE/blob/28ac2e09b82b37bf12f4aefca903bf03e19080ad/training_config/config.jsonnet#L8

**Comment by Lukafandi** [comment]
Thank you... while going through all the closed and opened issues 

I think I ran into similar issues with rdyzakya... I think something more need to be done when changing the pretrain model.

I ran the sample data given with another bert([bert-base-multilingual-cased](https://huggingface.co/bert-base-multilingual-cased)). 

predout.json will not be generated. 

![image](https://user-images.githubusercontent.com/108794735/201484612-953d6e7a-35d2-4c00-83c0-7148980dc892.png)
![image](https://user-images.githubusercontent.com/108794735/201484721-72504d87-1e08-454f-b8d0-b7ec5c923dfd.png)


In standard execution it will continue with trainer.optimizer.type however by changing the model it stop in a step prior to that which is trainer.trainer_callbacks = None

In the mean time ill keep trying to understand allennlp module...

**Comment by chiayewken** [comment]
Hi, for easier debugging, you can git pull the latest commit [16c7937](https://github.com/chiayewken/Span-ASTE/commit/16c7937e38304b47fccc30823c740b2aa424c565) which allows you to debug into the specific allennlp code which caused the error. Take note that you also need to update the git commit version in the top notebook cell and train the model from scratch, hope it helps!

**Comment by Lukafandi** [comment]
Well billion gratitude now it worked and I just noticed the needs to update the commit version in notebook. It does help us to get around. Another error occurred but I guess it involving those who would love run the system using the pretrained SpanModel weights for prediction section. 

![image](https://user-images.githubusercontent.com/108794735/201535233-95e4c71f-bf19-4f1c-b66b-b2b0e7564c11.png)

For a full error I would have to click the hidden frame, but just doing my best.

![image](https://user-images.githubusercontent.com/108794735/201535316-d7f48653-b2c0-4848-8ac1-18ba903c56d6.png)
