### ISSUE TITLE
Using the notebook when there is no GPU

### ISSUE THREAD

**Issue by xiaoqingwan** [chiayewken/Span-ASTE#21]
Hello! Thank you for sharing this work! I was wondering how I can use the demo notebook locally when there is no GPU？

When running the cell under "# Use pretrained SpanModel weights for prediction, " I got this error:

2022-07-06 12:28:07,840 - INFO - allennlp.common.plugins - Plugin allennlp_models available
Traceback (most recent call last):
  File "/Users/xiaoqingwan/opt/miniconda3/envs/absa/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/Users/xiaoqingwan/opt/miniconda3/envs/absa/lib/python3.7/site-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/Users/xiaoqingwan/opt/miniconda3/envs/absa/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 118, in main
    args.func(args)
  File "/Users/xiaoqingwan/opt/miniconda3/envs/absa/lib/python3.7/site-packages/allennlp/commands/predict.py", line 205, in _predict
    predictor = _get_predictor(args)
  File "/Users/xiaoqingwan/opt/miniconda3/envs/absa/lib/python3.7/site-packages/allennlp/commands/predict.py", line 105, in _get_predictor
    check_for_gpu(args.cuda_device)
  File "/Users/xiaoqingwan/opt/miniconda3/envs/absa/lib/python3.7/site-packages/allennlp/common/checks.py", line 131, in check_for_gpu
    " 'trainer.cuda_device=-1' in the json config file." + torch_gpu_error
allennlp.common.checks.ConfigurationError: Experiment specified a GPU but none is available; if you want to run on CPU use the override 'trainer.cuda_device=-1' in the json config file.
module 'torch.cuda' has no attribute '_check_driver'

I changed cuda_device to -1 in the jsonnet files from your folder training_config. But still no luck.

**Comment by chiayewken** [comment]
Hi, sorry the CPU inference seems not supported yet, we will try to implement and test it in the future.

**Comment by Jurys22** [comment]
I am only running it on CPU (windows). 
What I've done is:

- template.libsonnet: put the two mentions to cuda_device as  cuda_device :: -1,
- when calling the python script avoid calling also the argument for cuda

hope it helps

**Comment by dipanmoy** [comment]
@chiayewken Thanks for opening the thread. I will check and get back to you. Kindly don't close this thread for next few days.

**Comment by jasonhuynh83** [comment]
> I am only running it on CPU (windows). What I've done is:
> 
> * template.libsonnet: put the two mentions to cuda_device as  cuda_device :: -1,
> * when calling the python script avoid calling also the argument for cuda
> 
> hope it helps

Unfortunately I am unable to get this to run on MacOS CPU, I've set the template.libsonnet cuda_deivce to -1, how do I avoid calling the argument for cuda in the python script?

**Comment by Jurys22** [comment]
Following the main file that I copied here

I don't use this parameter  --trainer__cuda_device "$DEVICE" \

_rm -rf model*
mkdir -p models
$PYTHON aste/main.py \
  --names 14lap,14lap,14lap,14lap,14lap,14res,14res,14res,14res,14res,15res,15res,15res,15res,15res,16res,16res,16res,16res,16res \
  --seeds 0,1,12,123,1234,0,1,12,123,1234,0,1,12,123,1234,0,1,12,123,1234 \
  --trainer__cuda_device "$DEVICE" \
  --trainer__num_epochs 10 \
  --trainer__checkpointer__num_serialized_models_to_keep 1 \
  --model__span_extractor_type "endpoint" \
  --model__modules__relation__use_single_pool False \
  --model__relation_head_type "proper" \
  --model__use_span_width_embeds True \
  --model__modules__relation__use_distance_embeds True \
  --model__modules__relation__use_pair_feature_multiply False \
  --model__modules__relation__use_pair_feature_maxpool False \
  --model__modules__relation__use_pair_feature_cls False \
  --model__modules__relation__use_span_pair_aux_task False \
  --model__modules__relation__use_span_loss_for_pruners False \
  --model__loss_weights__ner 1.0 \
  --model__modules__relation__spans_per_word 0.5 \
  --model__modules__relation__neg_class_w_eight -1
