### ISSUE TITLE
command命令错误

### ISSUE THREAD

**Issue by lzf00** [chiayewken/Span-ASTE#23]
{'command': 'cd /home/data2/yj/Span-ASTE && allennlp train outputs/14lap/seed_0/config.jsonnet --serialization-dir outputs/14lap/seed_0/weights --include-package span_model'}
/bin/sh: allennlp: 未找到命令，请问这个在什么文件里改，一直没找到。。。

**Comment by chiayewken** [comment]
你好，请问是否装了 allennlp 吗？[这里](https://github.com/chiayewken/Span-ASTE#installation)
另外，你可以试一试这里的示范代码：https://github.com/chiayewken/Span-ASTE/blob/main/demo.ipynb

**Comment by lzf00** [comment]
好的，我又按照教程做了一遍，但是碰到了一个新问题，TypeError: BiAffineSpanExtractor.forward: `sequence_mask` is not present
![image](https://user-images.githubusercontent.com/51185068/178395551-5b39dec5-245f-42e6-aad8-59cc62ee0619.png)

**Comment by chiayewken** [comment]
这可能是版本问题，请问你的 python，allennlp 和 torch 是什么版本？

**Comment by lzf00** [comment]
python3.7，allennlp1.2，torch1.7，我知道了，是我的显卡是3090的，需要安装cuda11+，这个环境装的是10.2导致显卡不能使用，感谢回复

**Comment by hash123456789** [comment]
您好，请问如何在训练时对模型进行调试呢，用allennlp train这个命令如何才能断点调试

**Comment by chiayewken** [comment]
关于 allennlp train，不太好做 debugging，你可以在训练之前分别在模型部分做unit tests

**Comment by motuomumu** [comment]
> 好的，我又按照教程做了一遍，但是碰到了一个新问题，TypeError: BiAffineSpanExtractor.forward: `sequence_mask` is not present ![image](https://user-images.githubusercontent.com/51185068/178395551-5b39dec5-245f-42e6-aad8-59cc62ee0619.png)

您好，我也遇到了相同的问题，请问您解决了吗？有什么办法吗？

**Comment by chiayewken** [comment]
Hi the error may be due to conflicting versions of code and pretrained model, can you run "git checkout f53ec3" and reinstall the requirements.txt?
