### ISSUE TITLE
Error running demo 

### ISSUE THREAD

**Issue by Pinerush** [chiayewken/Span-ASTE#25]
I get an error running the 3rd cell in the demo saying "pred_out.json" does not exist

**Comment by chiayewken** [comment]
Hi, can you provide more details on your specific hardware setup and environment?
Currently, I'm unable to reproduce your error in the [demo colab notebook](https://colab.research.google.com/drive/1F9zW_nVkwfwIVXTOA_juFDrlPz5TLjpK?usp=sharing).

**Comment by Pinerush** [comment]
It was an error on the Jupiter notebook, worked fine on colab

**Comment by rdyzakya** [comment]
Oh yes, I found this error too if I change the random seed

**Comment by dinhgiangltk** [comment]
Hi @chiayewken, I have used the Google Colab notebook to run the demo codes. And the mentioned-above error has appeared. I guested that because the JSON file was opened without a defined mode, then I tried to edit it to be mode 'w'. But the same error was still there. Could you please help me with that?
![image](https://user-images.githubusercontent.com/58968330/182807329-c6561ae0-011c-40f4-9feb-6197e31f7197.png)

**Comment by dinhgiangltk** [comment]
Hi @rdyzakya, you mean if you do not change the random seed (random_seed=0), you do not get the error, do you?

**Comment by rdyzakya** [comment]
@dinhgiangltk if I recall, yes as you said, but I try it just now and it was okay. this become a problem when I use another dataset

**Comment by dinhgiangltk** [comment]
@rdyzakya but I ran the same codes and the error appeared. :(

**Comment by dipanmoy** [comment]
Yes, until this morning everything was fine. But now it's giving this pred_out file is missing error. Also, unable to retrain model using our own dataset. The training runs for sometime and then stops just before the epoch phase starts. Also doesn't throw up any error.

**Comment by chiayewken** [comment]
Hi everyone, sorry for the delay. I tried to run the [colab demo](https://colab.research.google.com/drive/1F9zW_nVkwfwIVXTOA_juFDrlPz5TLjpK?usp=sharing#scrollTo=izKXA4b6-oIv) and change the random seed for training (eg from 0 to 4) but it runs smoothly and there is no error. If your training stage doesn't work, please save the entire terminal log and attach the log file here as the allennlp error may be quite far up.

For those who face the error in cell 3 for the pretrained weights, can you check that the pretrained_14lap weights file is downloaded? If you still face the error, please delete the local files and try again. If possible, it will be useful to know your specific hardware setup and environment.

**Comment by dipanmoy** [comment]
@chiayewken I was able to run all the cells as well as train my own data yesterday.
