### ISSUE TITLE
Train for ATE/OTE along with triplets

### ISSUE THREAD

**Issue by sidvenkat1988** [chiayewken/Span-ASTE#28]
Hi, my task involves detecting standalone aspects (aspects without opinions) along with detecting aspect-opinion-triplets. Can I train this model for the same? 

If yes, is there any difference in the way I should prepare my training data, or make any changes in the training configuration?

**Comment by chiayewken** [comment]
Hi, when the span model is training, it uses the [SpanModelDocument](https://github.com/chiayewken/Span-ASTE/blob/92bc9a039a27760b6cecdda40bdadebed9772c6b/aste/main.py#L36) which currently specifies the spans which are contained in each sentiment triplet. Hence, to support standalone spans (independent aspects or opinions), you just need to modify this part of the data pipeline to include the spans that you need.
