### ISSUE TITLE
No such file or directory: 'pretrained_14res/temp_data/pred_out.json'

### ISSUE THREAD

**Issue by dipanmoy** [chiayewken/Span-ASTE#29]
Installed it successfully in MAC OS but getting the error pred_out.json not found. Not sure why is this working successfully in colab but not when I am installing it in my local machine. Can any one help me . I have downloaded the folder correctly. Contains all the required files. I have tried with 14lap and 14res but both have same issue. 
<img width="1009" alt="Screenshot 2022-09-22 at 7 48 09 PM" src="https://user-images.githubusercontent.com/109131004/191772846-a5495341-f901-4791-aca1-62298c4ad1a8.png">

**Comment by chiayewken** [comment]
Hi, when running on Mac without GPU, you can refer to this thread: https://github.com/chiayewken/Span-ASTE/issues/21#issuecomment-1191516824
