### ISSUE TITLE
IndexError: List assignment index out of range

### ISSUE THREAD

**Issue by jasonhuynh83** [chiayewken/Span-ASTE#30]
I've annotated my own data and tried to train the model with the annotated data, and run into this error here (see below). The command runs successfully, but the model doesn't train on the annotated data, going into the out.log files we see this error. The annotated data follows the correct format as I'm able to preview it in the Data Exploration command. Any help would be appreciated please! :) 

![image](https://user-images.githubusercontent.com/89210643/192614932-736d8211-b636-4c77-9f8b-a652565a72e0.png)

**Comment by chiayewken** [comment]
Hi, it may be due to the tag_maker which is an unused module. I have removed this module in the code so you may update the repo to the latest commit and please try again.

**Comment by jasonhuynh83** [comment]
Hello, it looks like it works now, thanks!
