### ISSUE TITLE
evaluation and predict test

### ISSUE THREAD

**Issue by arroyoaaa** [chiayewken/Span-ASTE#31]
Excuse me, how to you calculate the precision, recall and FScore?您好，请问您是用什么方法（公式）计算精确率、召回率和F1值？
And what do the last two numbers mean in predict test of each sample?（as shown below）以及在每个样本的预测结果中的最后两个数字代表什么意思呢？

![捕获](https://user-images.githubusercontent.com/94780438/195841271-e3058236-8294-4a6f-bc9c-058921a87153.PNG)

**Comment by chiayewken** [comment]
Hi, the two numbers are raw scores and softmax scores: https://github.com/chiayewken/Span-ASTE/issues/14#issuecomment-1034495370

Regarding the precision/recall/f1, we use micro f1 as shown here: https://github.com/chiayewken/Span-ASTE/blob/9e2b93d09b7e7ef70e2a8285cc9da5ea41b20f1d/aste/wrapper.py#L99
