### ISSUE TITLE
dictionary value

### ISSUE THREAD

**Issue by Lukafandi** [chiayewken/Span-ASTE#33]
Hi I encounter these issues while running through colab demo.

Do I need to have a minimum amount of annotated data for the model to work. or maybe the annotation are not correct?

![image](https://user-images.githubusercontent.com/108794735/201405854-fc31d323-3a50-4151-b4c9-d281cd845280.png)

**Comment by Lafandi** [comment]
well somehow I manage to resolve this by upgrading ipython

!pip install Ipython --upgrade. 

I'm not so sure either.

**Comment by Lukafandi** [comment]
I managed to solve this by ensuring in the data there is no extra line in after the last sentences. This can be closed :)
