### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by FanY1999** [chiayewken/Span-ASTE#4]
On the one hand,Do you have any preprocessing of the dataset? Since I didn't see the data folder in this repo. Can I just drop the ASTE-Dataset-V2 into the corresponding folder without any preprocess?

On the other hand,I can't find your code for processing the ASTE-Dataset-V2 data set, the relevant code seems to be processing the V1 data set. (evaluation.py->class TagReader->def read_inst->(line 159))

**Comment by chiayewken** [comment]
Hi, we are indeed using the V2 data, and the call to data preprocessing can be found here in [main.py line 174](https://github.com/chiayewken/Span-ASTE/blob/39863f8f8a988a83eb04d43a7834df178c3f22b0/aste/main.py#L174). 
The evaluation code is general and not specific to V1 or V2 data.
When you run setup.sh, the data will be downloaded to Span-ASTE/aste/data, and you can replace the files with your own data as long as the format is the same.
Hope this is helpful!

**Comment by FanY1999** [comment]
> Hi, we are indeed using the V2 data, and the call to data preprocessing can be found here in [main.py line 174](https://github.com/chiayewken/Span-ASTE/blob/39863f8f8a988a83eb04d43a7834df178c3f22b0/aste/main.py#L174). The evaluation code is general and not specific to V1 or V2 data. When you run setup.sh, the data will be downloaded to Span-ASTE/aste/data, and you can replace the files with your own data as long as the format is the same. Hope this is helpful!

thanks for your reply！
I didn’t look at the files carefully before,Now I have reproduced it successfully
