### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by arroyoaaa** [chiayewken/Span-ASTE#5]
Excuse me，how do you label the data to make the input format be as follows：

Exactly as posted plus a great value .####Exactly=O as=O posted=O plus=O a=O great=O value=T-POS .=O####Exactly=O as=O posted=O plus=O a=O great=S value=O .=O####[([6], [5], 'POS')]
The specs are pretty good too .####The=O specs=T-POS are=O pretty=O good=O too=O .=O####The=O specs=O are=O pretty=O good=S too=O .=O####[([1], [4], 'POS')]

**Comment by chiayewken** [comment]
Hi, the original description of the basic data format can be found here: https://github.com/xuuuluuu/SemEval-Triplet-data/blob/master/README.md#data-description

Regarding the tagging format, there are two parts for the target terms and aspect terms respectively. 
For the target terms, "Exactly=O as=O posted=O plus=O a=O great=O value=T-POS .=O" means that "value" is a target term with positive sentiment polarity.

For the aspect terms, "Exactly=O as=O posted=O plus=O a=O great=S value=O .=O" means that "great" is an aspect term with positive sentiment polarity.

In some cases, the sentence may contain two or more sentiment triplets. Hence, we repeat the "T" or "S" symbol to denote corresponding target-aspect pairs. For example, the target tags "Exactly=O as=O posted=O plus=O a=O great=O value=T-POS and=O cheap=O price=TT-POS .=O" and aspect tags "Exactly=O as=O posted=O plus=O a=O great=S value=O and=O cheap=SS price=O .=O" denotes that there are two triplets (value, great, Positive) and (price, cheap, Positive).

**Comment by arroyoaaa** [comment]
Thank you so much！！I still have a question to ask you. 

Have you ever used a tool or code to label the data? I think the tagging format  is a bit complicated, so I want to know if you have done any batch processing. Or do you adjust the tagging format one by one?

I'd really appreciate it if you could answer!

**Comment by xuuuluuu** [comment]
Hi @arroyoaaa, I recommend using the below format for labeling such datasets:

Exactly as posted plus a great value .  [([6], [5], 'POS')]

The old tagging format should be ignored, as you can always retrieve the aspect terms, opinion terms, and the sentiment polarity information from the final triplets ([6], [5], 'POS').

**Comment by arroyoaaa** [comment]
oh，thank you！！
