### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by FengLingCong13** [chiayewken/Span-ASTE#6]
Hello, I have a question, I want to ask you. I use Pycharm to run your project, but report an error in the main.py file, prompt: ModuleNotFoundError: No module named '_jsonnet'. I guess the main reason because import _jsonnet  # noqa.
Can you tell me a solution? Thank you very much.
![微信图片_20211123164149](https://user-images.githubusercontent.com/45933255/142993128-71263770-2776-4413-97bb-65a61272dca0.png)

**Comment by chiayewken** [comment]
Hi, this may be an issue in the Python environment, can I check if you managed to run the setup.sh like in the [Colab Notebook?](https://colab.research.google.com/drive/1F9zW_nVkwfwIVXTOA_juFDrlPz5TLjpK?usp=sharing)

**Comment by chiayewken** [comment]
Sorry I don't have experience running the scripts on windows, so it may be better to run them using a linux environment instead as it is more widely supported. I saw that windows partially supports the linux environment with [WSL](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) but it may be an experimental feature.

**Comment by FengLingCong13** [comment]
Thank you for your patience
