### ISSUE TITLE
Questions about the Comparison of Single-word and Multi-word Spans

### ISSUE THREAD

**Issue by lixt47** [chiayewken/Span-ASTE#8]
Excuse me, I'd like to ask how did you divide the data and train the model in Comparison of Single-word and Multi-word Spans. I can't find the corresponding code in this link.
Also, are the experiment results reported in Comparison of Single-word and Multi-word Spans obtained by training the model with the whole dataset and then testing only with the Single-word/Multi-word data of the test set? Or just training the model the Single-word/Multi-word data of the train set?

**Comment by chiayewken** [comment]
Hi, the model is trained on the whole dataset, then the test data is split and evaluated separately for single and multi-word spans. Single-Word: Both target and opinion terms in a triplet are single-word spans, Multi-Word: At least one of the target or opinion terms in a triplet is a multi-word span.
